import { Recipe } from './types/recipe';

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Butter Chicken",
    description: "A rich and creamy curry dish featuring tender chicken pieces in a spiced tomato, butter, and cream sauce.",
    image: "https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    cookTime: 45,
    servings: 4,
    categories: ["Dinner", "Indian", "Non-vegetarian"],
    ingredients: [
      "1 lb chicken thighs, cut into pieces",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "2 tbsp butter",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "1 cup heavy cream",
      "1 tsp garam masala",
      "1 tsp kasuri methi (dried fenugreek leaves)",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    instructions: [
      "Marinate chicken with yogurt, ginger-garlic paste, turmeric, and red chili powder for 30 minutes.",
      "Heat butter in a pan and cook marinated chicken until golden brown.",
      "In another pan, sauté onions until translucent.",
      "Add tomato puree and cook until oil separates.",
      "Add cooked chicken, cream, garam masala, and kasuri methi.",
      "Simmer for 10-15 minutes until the sauce thickens.",
      "Garnish with fresh coriander and serve hot with naan or rice."
    ],
    nutrition: {
      calories: "450 kcal",
      protein: "28g",
      carbs: "12g",
      fat: "32g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "45 mins",
    dietary: "Non-vegetarian"
  },
  {
    id: "2",
    title: "Vegetable Biryani",
    description: "A fragrant Indian rice dish with mixed vegetables, aromatic spices, and basmati rice.",
    image: "https://i.pinimg.com/736x/cd/1f/c3/cd1fc304a511b2d254804cfa8972e12a.jpg",
    cookTime: 45,
    servings: 6,
    categories: ["Dinner", "Indian", "Vegetarian"],
    ingredients: [
      "2 cups basmati rice",
      "2 cups mixed vegetables (carrots, peas, beans, cauliflower)",
      "1 onion, sliced",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "1 cup yogurt",
      "2 tbsp biryani masala",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "4-5 green cardamoms",
      "2-3 cinnamon sticks",
      "4-5 cloves",
      "1 bay leaf",
      "Fresh mint and coriander leaves",
      "Saffron strands soaked in warm milk",
      "Ghee or oil",
      "Salt to taste"
    ],
    instructions: [
      "Wash and soak rice for 30 minutes.",
      "Parboil rice with whole spices until 70% cooked.",
      "In a pan, sauté onions until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add vegetables, biryani masala, turmeric, and red chili powder.",
      "Cook vegetables until tender.",
      "Layer rice and vegetable mixture in a heavy-bottomed pan.",
      "Add saffron milk, mint, and coriander leaves between layers.",
      "Cover and cook on low heat for 20-25 minutes.",
      "Serve hot with raita."
    ],
    nutrition: {
      calories: "380 kcal",
      protein: "8g",
      carbs: "65g",
      fat: "12g"
    },
    cuisine: "Indian",
    difficulty: "Hard",
    time: "60 mins",
    dietary: "Vegetarian"
  },
  {
    id: "3",
    title: "Masala Dosa",
    description: "Crispy fermented rice and lentil crepes filled with spiced potato filling, served with sambar and chutney.",
    image: "https://i.pinimg.com/736x/6e/10/c7/6e10c7c0c11d6e2a28d6c51c3877774a.jpg",
    cookTime: 30,
    servings: 4,
    categories: ["Breakfast", "Indian", "Vegetarian"],
    ingredients: [
      "2 cups rice",
      "1 cup urad dal (black gram)",
      "1/2 tsp fenugreek seeds",
      "Salt to taste",
      "For potato filling:",
      "4 potatoes, boiled and mashed",
      "1 onion, finely chopped",
      "2 green chilies, chopped",
      "1 tsp mustard seeds",
      "1 tsp turmeric powder",
      "Curry leaves",
      "Oil for cooking"
    ],
    instructions: [
      "Soak rice, urad dal, and fenugreek seeds separately for 6-8 hours.",
      "Grind to make a smooth batter and ferment overnight.",
      "For potato filling, heat oil and add mustard seeds.",
      "Add onions, green chilies, and curry leaves.",
      "Add mashed potatoes and spices, cook for 5 minutes.",
      "Heat a griddle and pour batter to make thin dosas.",
      "Cook until crispy, add potato filling, and fold.",
      "Serve hot with sambar and coconut chutney."
    ],
    nutrition: {
      calories: "320 kcal",
      protein: "6g",
      carbs: "58g",
      fat: "8g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "30 mins",
    dietary: "Vegetarian"
  },
  {
    id: "4",
    title: "Chicken Tikka Masala",
    description: "Tender chicken pieces marinated in spices and yogurt, grilled and served in a rich, creamy tomato-based curry.",
    image: "https://i.pinimg.com/736x/2a/86/40/2a864028c6cf41e9d037bdf6e74e07be.jpg",
    cookTime: 50,
    servings: 4,
    categories: ["Dinner", "Indian", "Non-vegetarian"],
    ingredients: [
      "1 lb chicken breast, cut into pieces",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "2 tbsp oil",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "1 cup heavy cream",
      "1 tsp kasuri methi",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    instructions: [
      "Marinate chicken with yogurt, ginger-garlic paste, and spices for 2 hours.",
      "Grill or bake chicken until cooked through.",
      "In a pan, heat oil and sauté onions until golden.",
      "Add tomato puree and cook until oil separates.",
      "Add grilled chicken, cream, and kasuri methi.",
      "Simmer for 10-15 minutes until the sauce thickens.",
      "Garnish with fresh coriander and serve with naan or rice."
    ],
    nutrition: {
      calories: "420 kcal",
      protein: "32g",
      carbs: "15g",
      fat: "28g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "50 mins",
    dietary: "Non-vegetarian"
  },
  {
    id: "5",
    title: "Palak Paneer",
    description: "Fresh spinach curry with soft cottage cheese cubes, seasoned with aromatic spices.",
    image: "https://i.pinimg.com/736x/c1/e5/8d/c1e58dc5b850ed2a576a325de6339719.jpg",
    cookTime: 35,
    servings: 4,
    categories: ["Dinner", "Indian", "Vegetarian"],
    ingredients: [
      "500g fresh spinach",
      "200g paneer (cottage cheese)",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "1 tsp garam masala",
      "2 tbsp oil",
      "Salt to taste",
      "Fresh cream for garnish"
    ],
    instructions: [
      "Blanch spinach and puree it.",
      "Cut paneer into cubes and lightly fry them.",
      "Heat oil and add cumin seeds.",
      "Add onions and sauté until translucent.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add tomato puree and cook until oil separates.",
      "Add spinach puree and cook for 5 minutes.",
      "Add paneer cubes and garam masala.",
      "Simmer for 5 minutes and garnish with cream."
    ],
    nutrition: {
      calories: "280 kcal",
      protein: "12g",
      carbs: "18g",
      fat: "20g"
    },
    cuisine: "Indian",
    difficulty: "Easy",
    time: "35 mins",
    dietary: "Vegetarian"
  },
  {
    id: "6",
    title: "Chole Bhature",
    description: "Spiced chickpea curry served with fluffy deep-fried bread.",
    image: "https://i.pinimg.com/736x/a2/6b/1f/a26b1fdaa37db59231826d870edaa391.jpg",
    cookTime: 40,
    servings: 4,
    categories: ["Breakfast", "Indian", "Vegetarian"],
    ingredients: [
      "2 cups chickpeas, soaked overnight",
      "2 onions, finely chopped",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "2 tsp chole masala",
      "1 tsp garam masala",
      "For bhature:",
      "2 cups all-purpose flour",
      "1/2 cup yogurt",
      "1 tsp baking powder",
      "Salt to taste",
      "Oil for deep frying"
    ],
    instructions: [
      "Pressure cook chickpeas until soft.",
      "In a pan, sauté onions until golden.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add tomatoes and spices, cook until oil separates.",
      "Add cooked chickpeas and simmer for 10 minutes.",
      "For bhature, mix flour, yogurt, baking powder, and salt.",
      "Knead into a soft dough and rest for 2 hours.",
      "Roll into circles and deep fry until puffed and golden.",
      "Serve hot chole with bhature."
    ],
    nutrition: {
      calories: "450 kcal",
      protein: "15g",
      carbs: "65g",
      fat: "18g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "40 mins",
    dietary: "Vegetarian"
  },
  {
    id: "7",
    title: "Chicken Curry",
    description: "Classic Indian chicken curry with aromatic spices and rich gravy.",
    image: "https://i.pinimg.com/736x/34/3d/83/343d8334156239fed09d3757763914c2.jpg",
    cookTime: 45,
    servings: 4,
    categories: ["Dinner", "Indian", "Non-vegetarian"],
    ingredients: [
      "1 kg chicken, cut into pieces",
      "2 onions, finely chopped",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "2 tbsp oil",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    instructions: [
      "Heat oil and sauté onions until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add chicken pieces and cook until they change color.",
      "Add all dry spices and cook for 5 minutes.",
      "Add tomatoes and cook until soft.",
      "Add water and simmer for 20-25 minutes until chicken is tender.",
      "Garnish with fresh coriander and serve hot with rice or roti."
    ],
    nutrition: {
      calories: "380 kcal",
      protein: "28g",
      carbs: "12g",
      fat: "25g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "45 mins",
    dietary: "Non-vegetarian"
  },
  {
    id: "8",
    title: "Idli Sambar",
    description: "Soft, fluffy rice cakes served with spiced lentil soup.",
    image: "https://i.pinimg.com/736x/e2/90/7e/e2907ec58db3447f2dd8dad00c832c0c.jpg",
    cookTime: 30,
    servings: 4,
    categories: ["Breakfast", "Indian", "Vegetarian"],
    ingredients: [
      "For idli:",
      "2 cups rice",
      "1 cup urad dal",
      "1/2 tsp fenugreek seeds",
      "Salt to taste",
      "For sambar:",
      "1 cup toor dal",
      "2 cups mixed vegetables",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "2 tbsp sambar powder",
      "1 tsp turmeric powder",
      "Tamarind pulp",
      "Salt to taste",
      "For tempering:",
      "1 tsp mustard seeds",
      "1 tsp cumin seeds",
      "Curry leaves",
      "2 tbsp oil"
    ],
    instructions: [
      "Soak rice and urad dal separately for 6-8 hours.",
      "Grind to make a smooth batter and ferment overnight.",
      "Pour batter into idli molds and steam for 10-12 minutes.",
      "For sambar, pressure cook dal and vegetables.",
      "In a pan, heat oil and add tempering ingredients.",
      "Add cooked dal, vegetables, and spices.",
      "Simmer for 10 minutes and serve hot with idlis."
    ],
    nutrition: {
      calories: "280 kcal",
      protein: "8g",
      carbs: "52g",
      fat: "6g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "30 mins",
    dietary: "Vegetarian"
  },
  {
    id: "9",
    title: "Pav Bhaji",
    description: "Spiced mashed vegetables served with buttered bread rolls.",
    image: "https://i.pinimg.com/736x/bd/03/1b/bd031b26343b8c2cc6f035d68f8d90ab.jpg",
    cookTime: 40,
    servings: 4,
    categories: ["Street Food", "Indian", "Vegetarian"],
    ingredients: [
      "4 potatoes, boiled and mashed",
      "2 cups mixed vegetables (cauliflower, peas, carrots)",
      "2 onions, finely chopped",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "2 tbsp pav bhaji masala",
      "1 tsp red chili powder",
      "Butter for cooking",
      "8 pav (bread rolls)",
      "Lemon juice",
      "Fresh coriander for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Boil and mash all vegetables.",
      "Heat butter and sauté onions until translucent.",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add tomatoes and cook until soft.",
      "Add mashed vegetables and all spices.",
      "Cook for 10-15 minutes, mashing continuously.",
      "Toast pav with butter.",
      "Serve hot bhaji with buttered pav and chopped onions."
    ],
    nutrition: {
      calories: "350 kcal",
      protein: "10g",
      carbs: "45g",
      fat: "18g"
    },
    cuisine: "Indian",
    difficulty: "Easy",
    time: "40 mins",
    dietary: "Vegetarian"
  },
  {
    id: "10",
    title: "Vada Pav",
    description: "Spicy potato fritters served in a bun with chutneys.",
    image: "https://i.pinimg.com/736x/54/77/33/54773366f4853cf55c8cb2c8bf30ca64.jpg",
    cookTime: 35,
    servings: 4,
    categories: ["Street Food", "Indian", "Vegetarian"],
    ingredients: [
      "For vada:",
      "4 potatoes, boiled and mashed",
      "2 green chilies, chopped",
      "1 inch ginger, grated",
      "1 tsp mustard seeds",
      "Curry leaves",
      "1 tsp turmeric powder",
      "For batter:",
      "1 cup gram flour",
      "1/4 tsp baking soda",
      "Water as needed",
      "For serving:",
      "8 pav (bread rolls)",
      "Green chutney",
      "Sweet chutney",
      "Oil for deep frying"
    ],
    instructions: [
      "Mix mashed potatoes with spices and make balls.",
      "Make a batter with gram flour and baking soda.",
      "Dip potato balls in batter and deep fry until golden.",
      "Toast pav with butter.",
      "Spread chutneys on pav.",
      "Place vada in pav and serve hot."
    ],
    nutrition: {
      calories: "320 kcal",
      protein: "8g",
      carbs: "42g",
      fat: "15g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "35 mins",
    dietary: "Vegetarian"
  },
  {
    id: "11",
    title: "Dhokla",
    description: "Steamed savory cake made from fermented rice and chickpea flour.",
    image: "https://i.pinimg.com/736x/3f/d4/a3/3fd4a3b508703474aadfe08678c1ef81.jpg",
    cookTime: 30,
    servings: 4,
    categories: ["Breakfast", "Indian", "Vegetarian"],
    ingredients: [
      "1 cup gram flour",
      "1 cup rice flour",
      "1 cup yogurt",
      "1 tsp ginger paste",
      "1 tsp green chili paste",
      "1 tsp eno fruit salt",
      "1 tsp turmeric powder",
      "For tempering:",
      "1 tsp mustard seeds",
      "1 tsp sesame seeds",
      "Curry leaves",
      "2 tbsp oil",
      "Salt to taste"
    ],
    instructions: [
      "Mix gram flour, rice flour, and yogurt to make a smooth batter.",
      "Add ginger paste, green chili paste, and salt.",
      "Add eno fruit salt just before steaming.",
      "Pour into greased plate and steam for 15-20 minutes.",
      "Prepare tempering with mustard seeds, sesame seeds, and curry leaves.",
      "Pour tempering over dhokla and cut into pieces.",
      "Serve with green chutney."
    ],
    nutrition: {
      calories: "180 kcal",
      protein: "6g",
      carbs: "28g",
      fat: "5g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "30 mins",
    dietary: "Vegetarian"
  },
  {
    id: "12",
    title: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas.",
    image: "https://i.pinimg.com/736x/1c/68/fc/1c68fc95d5e356e843e97679b519959f.jpg",
    cookTime: 45,
    servings: 6,
    categories: ["Snacks", "Indian", "Vegetarian"],
    ingredients: [
      "For dough:",
      "2 cups all-purpose flour",
      "4 tbsp oil",
      "Salt to taste",
      "Water as needed",
      "For filling:",
      "4 potatoes, boiled and diced",
      "1 cup green peas",
      "1 onion, finely chopped",
      "2 green chilies, chopped",
      "1 tsp ginger paste",
      "1 tsp garam masala",
      "1 tsp coriander powder",
      "Oil for deep frying"
    ],
    instructions: [
      "Make dough with flour, oil, and salt.",
      "For filling, heat oil and sauté onions.",
      "Add spices and cook for 2 minutes.",
      "Add potatoes and peas, cook for 5 minutes.",
      "Roll dough into circles and cut in half.",
      "Make cones and fill with potato mixture.",
      "Seal edges and deep fry until golden brown.",
      "Serve hot with chutney."
    ],
    nutrition: {
      calories: "280 kcal",
      protein: "5g",
      carbs: "38g",
      fat: "12g"
    },
    cuisine: "Indian",
    difficulty: "Hard",
    time: "45 mins",
    dietary: "Vegetarian"
  },
  {
    id: "13",
    title: "Kheer",
    description: "Creamy rice pudding flavored with cardamom and nuts.",
    image: "https://i.pinimg.com/736x/4d/64/69/4d6469332c08595879ee5ceae4958882.jpg",
    cookTime: 40,
    servings: 4,
    categories: ["Dessert", "Indian", "Vegetarian"],
    ingredients: [
      "1/2 cup basmati rice",
      "1 liter milk",
      "1/2 cup sugar",
      "1/4 cup mixed nuts (almonds, cashews, pistachios)",
      "1/4 cup raisins",
      "1 tsp cardamom powder",
      "Saffron strands (optional)",
      "Ghee for frying nuts"
    ],
    instructions: [
      "Wash and soak rice for 30 minutes.",
      "Boil milk and add rice.",
      "Cook on low heat, stirring frequently.",
      "When rice is soft, add sugar.",
      "Fry nuts in ghee and add to kheer.",
      "Add cardamom powder and saffron.",
      "Cook until thick and creamy.",
      "Serve hot or cold."
    ],
    nutrition: {
      calories: "320 kcal",
      protein: "8g",
      carbs: "45g",
      fat: "12g"
    },
    cuisine: "Indian",
    difficulty: "Easy",
    time: "40 mins",
    dietary: "Vegetarian"
  },
  {
    id: "14",
    title: "Gulab Jamun",
    description: "Soft milk solids balls soaked in sugar syrup.",
    image: "https://i.pinimg.com/736x/41/77/92/4177920dbd75f39879704d84f9458473.jpg",
    cookTime: 35,
    servings: 6,
    categories: ["Dessert", "Indian", "Vegetarian"],
    ingredients: [
      "1 cup milk powder",
      "1/4 cup all-purpose flour",
      "1/4 tsp baking soda",
      "2 tbsp ghee",
      "Milk as needed",
      "For sugar syrup:",
      "2 cups sugar",
      "1 cup water",
      "4-5 cardamom pods",
      "Oil for deep frying"
    ],
    instructions: [
      "Mix milk powder, flour, and baking soda.",
      "Add ghee and enough milk to make a soft dough.",
      "Make small balls and keep aside.",
      "Prepare sugar syrup by boiling sugar and water.",
      "Add cardamom to syrup.",
      "Deep fry balls until golden brown.",
      "Soak in warm sugar syrup for 2-3 hours.",
      "Serve warm or cold."
    ],
    nutrition: {
      calories: "280 kcal",
      protein: "5g",
      carbs: "42g",
      fat: "12g"
    },
    cuisine: "Indian",
    difficulty: "Medium",
    time: "35 mins",
    dietary: "Vegetarian"
  },
  {
    id: "15",
    title: "Jalebi",
    description: "Crispy, spiral-shaped sweet soaked in sugar syrup.",
    image: "https://i.pinimg.com/736x/58/d0/ee/58d0ee20230696987b7fce4a3e56f479.jpg",
    cookTime: 30,
    servings: 6,
    categories: ["Dessert", "Indian", "Vegetarian"],
    ingredients: [
      "1 cup all-purpose flour",
      "1/4 cup yogurt",
      "1/4 tsp baking soda",
      "1/4 tsp turmeric powder",
      "For sugar syrup:",
      "2 cups sugar",
      "1 cup water",
      "1/2 tsp cardamom powder",
      "Oil for deep frying"
    ],
    instructions: [
      "Mix flour, yogurt, and baking soda to make a smooth batter.",
      "Add turmeric for color and ferment for 2 hours.",
      "Prepare sugar syrup by boiling sugar and water.",
      "Add cardamom to syrup.",
      "Pour batter in a spiral shape into hot oil.",
      "Fry until crispy and golden.",
      "Soak in warm sugar syrup for 2-3 minutes.",
      "Serve hot."
    ],
    nutrition: {
      calories: "320 kcal",
      protein: "4g",
      carbs: "58g",
      fat: "8g"
    },
    cuisine: "Indian",
    difficulty: "Hard",
    time: "30 mins",
    dietary: "Vegetarian"
  },
  {
    id: "16",
    title: "Rasgulla",
    description: "Soft cottage cheese balls soaked in sugar syrup.",
    image: "https://i.pinimg.com/736x/98/3a/e8/983ae84fe28972ce2016da5dbb27f7c9.jpg",
    cookTime: 50,
    servings: 6,
    categories: ["Dessert", "Indian", "Vegetarian"],
    ingredients: [
      "1 liter milk",
      "2 tbsp lemon juice",
      "2 cups sugar",
      "4 cups water",
      "1/4 tsp cardamom powder",
      "Ice water for cooling"
    ],
    instructions: [
      "Boil milk and add lemon juice to curdle.",
      "Strain through muslin cloth to get chenna.",
      "Knead chenna until smooth.",
      "Make small balls and keep aside.",
      "Prepare sugar syrup by boiling sugar and water.",
      "Add chenna balls to boiling syrup.",
      "Cook for 15-20 minutes until spongy.",
      "Cool in ice water and serve chilled."
    ],
    nutrition: {
      calories: "180 kcal",
      protein: "6g",
      carbs: "32g",
      fat: "4g"
    },
    cuisine: "Indian",
    difficulty: "Hard",
    time: "50 mins",
    dietary: "Vegetarian"
  },
  {
    id: "17",
    title: "Poha",
    description: "Flattened rice cooked with spices and vegetables.",
    image: "https://i.pinimg.com/736x/89/bf/1a/89bf1a21cd6cd8251e8c09cea7561ffa.jpg",
    cookTime: 20,
    servings: 4,
    categories: ["Breakfast", "Indian", "Vegetarian"],
    ingredients: [
      "2 cups poha (flattened rice)",
      "1 onion, finely chopped",
      "1 potato, diced",
      "2 green chilies, chopped",
      "1 tsp mustard seeds",
      "1 tsp turmeric powder",
      "Curry leaves",
      "2 tbsp oil",
      "Lemon juice",
      "Fresh coriander for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Wash poha and drain excess water.",
      "Heat oil and add mustard seeds.",
      "Add curry leaves and green chilies.",
      "Add onions and potatoes, cook until soft.",
      "Add turmeric and salt.",
      "Add poha and mix gently.",
      "Cook for 5 minutes on low heat.",
      "Garnish with coriander and serve hot."
    ],
    nutrition: {
      calories: "220 kcal",
      protein: "4g",
      carbs: "38g",
      fat: "6g"
    },
    cuisine: "Indian",
    difficulty: "Easy",
    time: "20 mins",
    dietary: "Vegetarian"
  },
  {
    id: "18",
    title: "Upma",
    description: "Semolina porridge with vegetables and spices.",
    image: "https://i.pinimg.com/736x/6d/63/84/6d638401bc12dde2154d7304776cd6db.jpg",
    cookTime: 25,
    servings: 4,
    categories: ["Breakfast", "Indian", "Vegetarian"],
    ingredients: [
      "1 cup semolina (rava)",
      "1 onion, finely chopped",
      "1 carrot, diced",
      "1/4 cup green peas",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "Curry leaves",
      "2 green chilies, chopped",
      "2 tbsp oil",
      "Lemon juice",
      "Fresh coriander for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Dry roast semolina until golden.",
      "Heat oil and add mustard seeds and urad dal.",
      "Add curry leaves and green chilies.",
      "Add vegetables and cook until soft.",
      "Add water and bring to boil.",
      "Add semolina and cook until thick.",
      "Garnish with coriander and serve hot."
    ],
    nutrition: {
      calories: "240 kcal",
      protein: "5g",
      carbs: "42g",
      fat: "6g"
    },
    cuisine: "Indian",
    difficulty: "Easy",
    time: "25 mins",
    dietary: "Vegetarian"
  }
]; 